// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAljmWTcC_Phuvc9jN56sTggmXY7gbw3AE',
    appId: '1:327523805214:web:cc48edc055916c59f8a60f',
    messagingSenderId: '327523805214',
    projectId: 'wastemanagement2-4dda3',
    authDomain: 'wastemanagement2-4dda3.firebaseapp.com',
    storageBucket: 'wastemanagement2-4dda3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9XWuYjwTjhMLEuDr9IeKowm6k6I7f3ZI',
    appId: '1:327523805214:android:92c9f5d864ec891af8a60f',
    messagingSenderId: '327523805214',
    projectId: 'wastemanagement2-4dda3',
    storageBucket: 'wastemanagement2-4dda3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2W0odW7ApRddnfzxUfA2fZtsS3B9pymQ',
    appId: '1:327523805214:ios:90136968056f4d73f8a60f',
    messagingSenderId: '327523805214',
    projectId: 'wastemanagement2-4dda3',
    storageBucket: 'wastemanagement2-4dda3.firebasestorage.app',
    iosClientId: '327523805214-4dbdi9s74no61hscgp1qj43bog4erhdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.wastemanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2W0odW7ApRddnfzxUfA2fZtsS3B9pymQ',
    appId: '1:327523805214:ios:90136968056f4d73f8a60f',
    messagingSenderId: '327523805214',
    projectId: 'wastemanagement2-4dda3',
    storageBucket: 'wastemanagement2-4dda3.firebasestorage.app',
    iosClientId: '327523805214-4dbdi9s74no61hscgp1qj43bog4erhdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.wastemanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAljmWTcC_Phuvc9jN56sTggmXY7gbw3AE',
    appId: '1:327523805214:web:235c3234f627f7e2f8a60f',
    messagingSenderId: '327523805214',
    projectId: 'wastemanagement2-4dda3',
    authDomain: 'wastemanagement2-4dda3.firebaseapp.com',
    storageBucket: 'wastemanagement2-4dda3.firebasestorage.app',
  );

}