name: waste_management

description: A Flutter app connecting homes to waste management companies for real-time waste collection.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  firebase_core: ^2.24.0

  firebase_auth: ^4.17.8

  cloud_firestore: ^4.17.0 

  firebase_database: ^10.4.9


dev_dependencies:
  
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true 