// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrbxdp6gCDMvx7bogD3GYRGrtsOeDnb5Q',
    appId: '1:653370404424:web:078a2de0d1c1a40bcc327d',
    messagingSenderId: '653370404424',
    projectId: 'myapp-84da2',
    authDomain: 'myapp-84da2.firebaseapp.com',
    storageBucket: 'myapp-84da2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGUMAxGLuEkMd125ymRKXEySPPBxPrbN8',
    appId: '1:653370404424:android:7c3ea3453e617e38cc327d',
    messagingSenderId: '653370404424',
    projectId: 'myapp-84da2',
    storageBucket: 'myapp-84da2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2pshtQOQl4Vms5UdLOQrW0BUjE3XvZiI',
    appId: '1:653370404424:ios:76202a83ab761678cc327d',
    messagingSenderId: '653370404424',
    projectId: 'myapp-84da2',
    storageBucket: 'myapp-84da2.firebasestorage.app',
    iosBundleId: 'com.example.wastemanagement2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2pshtQOQl4Vms5UdLOQrW0BUjE3XvZiI',
    appId: '1:653370404424:ios:76202a83ab761678cc327d',
    messagingSenderId: '653370404424',
    projectId: 'myapp-84da2',
    storageBucket: 'myapp-84da2.firebasestorage.app',
    iosBundleId: 'com.example.wastemanagement2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrbxdp6gCDMvx7bogD3GYRGrtsOeDnb5Q',
    appId: '1:653370404424:web:72109098d98565b2cc327d',
    messagingSenderId: '653370404424',
    projectId: 'myapp-84da2',
    authDomain: 'myapp-84da2.firebaseapp.com',
    storageBucket: 'myapp-84da2.firebasestorage.app',
  );
}
