name: wastemanagement
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  provider: ^6.1.5
  firebase_ui_auth: ^1.17.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_sign_in: ^7.1.1
  bloc: ^9.0.0
  meta: ^1.16.0
  location: ^8.0.1
  firebase_storage: ^12.4.9
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.2.2
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  sqflite: ^2.4.1
  intl: ^0.20.2
  badges: ^3.1.2
  timezone: ^0.9.4
  image_picker: ^1.1.2
  image: ^4.2.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ann.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - .env


